/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"


void
handle_file_1(char *host, char *name, char *act)
{
	CLIENT *clnt;
	char * *result_1;
	Request  response_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, HANDLE_FILE, PROG_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	response_1_arg.file = name;
	response_1_arg.action = act;

	result_1 = response_1(&response_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf ("Server Responses: %s\n", *result_1);
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 4) {
		printf ("Usage: %s Server_host Filename Action\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	handle_file_1 (host, argv[2], argv[3]);
exit (0);
}
