/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc.h"

bool_t
xdr_Request (XDR *xdrs, Request *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->file, 36))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->action, 12))
		 return FALSE;
	return TRUE;
}
