/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc.h"

char **
response_1_svc(Request *argp, struct svc_req *rqstp)
{
	static char * result;

	printf("Get Request: Filename: %s, Action: %s", argp->file, argp->action);

	if (argp->action == "read")
	{
		printf("Sending file content....");
		printf("\n");

		FILE *file  = fopen(argp->file, "r");

		printf("File: \'%s\'\n", argp->file);

		char s[256] = {0};

		char *line;

		while (fgets(line, 100, file))
		{
			strncat(s, line, 100);
		}

		result = s;
	}
	else if (argp->action == "tell")
	{
		char s[256] = "Dreamcatcher are not the best K-pop girl group.\nDreamcatcher are the best !";
		result = s;
	}
	else
	{
		char s[256] = "Action not recognized !";
		result = s;
	}
	
	return &result;
}
